-- Migration is auto-generated by sql2cpp
-- You can edit this file manually, but be ready to re-run generation

CREATE TYPE service.key_value_table_v0 AS (
    key CHARACTER VARYING,
    value CHARACTER VARYING
);
